<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="34550" started-at="2023-03-04T16:18:01Z" finished-at="2023-03-04T16:18:35Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="34550" started-at="2023-03-04T16:18:01Z" finished-at="2023-03-04T16:18:35Z">
      <class name="Android.test.eCommerce_tc_1">
        <test-method status="PASS" signature="Initialise()[pri:0, instance:Android.test.eCommerce_tc_1@6a79c292]" name="Initialise" is-config="true" duration-ms="20897" started-at="2023-03-04T21:48:01Z" finished-at="2023-03-04T21:48:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Initialise -->
        <test-method status="FAIL" signature="FillForm()[pri:0, instance:Android.test.eCommerce_tc_1@6a79c292]" name="FillForm" duration-ms="9581" started-at="2023-03-04T21:48:21Z" finished-at="2023-03-04T21:48:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Please ent your name] but found [Please enter your name]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Please ent your name] but found [Please enter your name]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at Android.test.eCommerce_tc_1.FillForm(eCommerce_tc_1.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FillForm -->
        <test-method status="PASS" signature="Teardown()[pri:0, instance:Android.test.eCommerce_tc_1@6a79c292]" name="Teardown" is-config="true" duration-ms="864" started-at="2023-03-04T21:48:34Z" finished-at="2023-03-04T21:48:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Teardown -->
      </class> <!-- Android.test.eCommerce_tc_1 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
